### ISSUE TITLE
Looking for maintainer!

### ISSUE THREAD

**Issue by hagen1778** [Vertamedia/chproxy#118]
I'm very sorry to everyone for this project being poorly maintained. It looks I have neither time nor inspiration to be a maintainer. I believe, there are a lot of great engineers more interested in this project than me.  Please, let me know if you want to become a maintainer for `chproxy`!

**Comment by vfoucault** [comment]
Hi @hagen1778 , we might be able (@contentsquare) to allocate some time from time to time to work on this. 

Keep me posted.

**Comment by hagen1778** [comment]
@vfoucault now has collaborator permissions! Thank you very much for volunteering! Please let me know if you have any questions or need assistance. Mail me to hagen1778 @ gmail.com
