### ISSUE TITLE
[Feature Request] Round Time from Grafana

### ISSUE THREAD

**Issue by iShift** [Vertamedia/chproxy#15]
Grafana generates query with time in seconds and is is very hard to cache it (because if i use time range from date to now - now change every second) 

It would be very cool if you can trim date in SQL with some options: by seconds,minutes,hours,days i think that feature can be implemented with REGex

what do you think?

**Comment by hagen1778** [comment]
Hi @iShift 
Actually our [datasource](https://github.com/Vertamedia/clickhouse-grafana) already do this via `Round` option:
https://user-images.githubusercontent.com/2902918/32843338-337f2efc-ca28-11e7-9bde-ec65faa3cdc9.png
Check feature-list for `CHProxy` at `Grafana` datasource: https://github.com/Vertamedia/clickhouse-grafana#chproxy-optional

**Comment by iShift** [comment]
cool! But what is 
_Set rounding **for `left`** interval border.
For example, if set `1m` - left order will be rounded to beginning of minute._

what mean left interval? only **from** part ?

**Comment by hagen1778** [comment]
When `Grafana's` time-picker is set to, let's say, `last 5m` - it means, for example, from 1513155300 to 1513155600 (1513155300 + 5*60). Where 1513155300 is left, and 1513155600 - right border.
Clickhouse datasource will generate next `WHERE` condition:
`... WHERE event_date >= toDate(1513155300) AND event_time >= toDateTime(1513155300)`
So you see, there is no `BETWEEN`, just `bigger or equal` condition on `left` time border. And all what we need is to round this border to value from `round` option. If `round` is set to `1m` - then all requests during 1min will have same timestamp value.

**Comment by iShift** [comment]
add comment to https://github.com/Vertamedia/clickhouse-grafana/issues/12, i think we can talk in to that issue, so i close this one.
