### ISSUE TITLE
Cache not working between browsers?

### ISSUE THREAD

**Issue by jpiper** [Vertamedia/chproxy#25]
Is CHproxy hashing the user-agent string or something similar as the cache key? I find that even though I can force-refresh the same page a million times and can verify the result comes from cache, if I switch to a different browser (or use cURL) the query gets re-run

**Comment by hagen1778** [comment]
Hi @jpiper 
Cache key consists of following params:
```
type Key struct {
	// Query must contain full request query.
	Query []byte

	// AcceptEncoding must contain 'Accept-Encoding' request header value.
	AcceptEncoding string

	// DefaultFormat must contain `default_format` query arg.
	DefaultFormat string

	// Database must contain `database` query arg.
	Database string

	// Compress must contain `compress` query arg.
	Compress string

	// Namespace is an optional cache namespace.
	Namespace string
}
```

The difference between browsers could be in `AcceptEncoding`. For example, GChrome accepts `gzip, deflate, sdch, br`, while Firefox only `gzip, deflate`.

**Comment by jpiper** [comment]
Ah, that explains it! I assumed it was caching the actual query, not the response data in it’s returned form. Seems like a bit of a bug to me - in my mind it makes sense to cache the raw response to account for different browsers (I guess you would then have to decide whether to compress on the fly each time or also cache the compressed responses).

I was trying to use a script a script to “warm” the cache for certain queries where it takes up to 20s to run, and was confused why it wasn’t working for me. I’ll have to run it with several queries with different accepts headers.

**Comment by jpiper** [comment]
Ah, it's even simpler.

Safari uses "br, gzip, deflate" and chrome uses "gzip, deflate, br"

May I recommend a simple fix: sort the items of the accept header so that the ordering doesn't affect the ability to cache or not.

**Comment by hagen1778** [comment]
Hi @jpiper 
see https://github.com/Vertamedia/chproxy/releases/tag/1.10.4

**Comment by jpiper** [comment]
I wonder if it's worth caching both the underlying query and also the compressed response, that way queries don't have to be re-run just because the compression method changes?

**Comment by hagen1778** [comment]
Change of AcceptEncoding header means that ClickHouse will also change  response compress method. And we must serve compressed response to the client who knows how to decompress it. That's why `chproxy`'s cache key consists of all parameters which could potentially affect the response.
