### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by jpiper** [Vertamedia/chproxy#27]
For deploying chproxy via kubernetes (or similar), it would be good if there was an endpoint like `/health` that could be used for [liveness and readiness checks](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/).

**Comment by hagen1778** [comment]
Hi @jpiper 
`chproxy` doesn't have a state to check in such endpoint. Things like successful reconfig or CH-cluster health are controlled by metrics. Without internal health checks it would be just `ping` endpoint which not make much sense.
I suggest you to use `/metrics` endpoint to see whether `chproxy` is alive.

**Comment by jpiper** [comment]
Ah that's a good idea, thanks!
