### ISSUE TITLE
External data for query processing

### ISSUE THREAD

**Issue by velichkin** [Vertamedia/chproxy#28]
I've noticed that chproxy doesn't support external data for queries. Documentation - https://clickhouse.yandex/docs/en/table_engines/external_data/

Example with clickhouse server:
`
$ echo -ne "1\n2\n3\n" > /tmp/testdata
$ curl -F 'testdata=@/tmp/testdata;' 'http://localhost:8123?user=user&password=password&query=SELECT+*+FROM+testdata&testdata_structure=id+UInt32'
`
Response:
`
1
2
3
`

Example with chproxy:
`
$ echo -ne "1\n2\n3\n" > /tmp/testdata
$ curl -F 'testdata=@/tmp/testdata;' 'http://localhost:9090?user=CHPROXY_USER&password=CHPROXY_PASSWORD&query=SELECT+*+FROM+testdata&testdata_structure=id+UInt32'
`
Response:
`
Code: 36, e.displayText() = DB::Exception: Neither structure nor types have not been provided for external table testdata. Use fields testdata_structure or testdata_types to do so., e.what() = DB::Exception
`

Are there any plans on fixing it?

**Comment by valyala** [comment]
Currently there are no plans for adding external data processing.

@hagen1778 , could you look whether it is enough to whitelist query args ending with `_structure` for external data support?

**Comment by hagen1778** [comment]
Hi @velichkin @valyala 
Totally forgot about this issue. I'll take a look as soon as possible but can't promise it will be soon. Any help is appreciated btw

**Comment by hagen1778** [comment]
see https://github.com/Vertamedia/chproxy/releases/tag/1.11.0
