### ISSUE TITLE
[Feature Request] support for enable_http_compression parameter

### ISSUE THREAD

**Issue by k1rk** [Vertamedia/chproxy#29]
Please add support of `enable_http_compression` parameter to get gziped responses from server.

According to clickhouse doc https://clickhouse.yandex/docs/en/interfaces/http_interface/

> Also standard gzip-based HTTP compression can be used. To send gzip compressed POST data just add Content-Encoding: gzip to request headers, and gzip POST body. To get response compressed, you need to add Accept-Encoding: gzip to request headers, and turn on ClickHouse setting called enable_http_compression.

**Comment by hagen1778** [comment]
see https://github.com/Vertamedia/chproxy/releases/tag/1.11.0
