### ISSUE TITLE
Add new allowed parameters

### ISSUE THREAD

**Issue by komex** [Vertamedia/chproxy#34]
Using chproxy make uncomfortable work with database tools like DBeaver or DbVisualiser because they uses query parameters to limit shown data.

Example:

```
POST /?compress=1&password=123&result_overflow_mode=break&extremes=0&max_result_rows=100&user=default&database=default HTTP/1.1
Content-Length: 83
Content-Type: text/plain; charset=UTF-8
Host: localhost
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_181)

SELECT * FROM "default"."table" FORMAT TabSeparatedWithNamesAndTypes;
```

chproxy cut parameters *result_overflow_mode*, *extremes* and *max_result_rows*, so when I open table in database tool ClickHouse tries to load ALL data from table instead of load only 100 rows.

Please, add this parameters to allowed.

**Comment by hagen1778** [comment]
Hi @komex 
Are they dynamically assigned? Could it be solved via [user params](https://github.com/Vertamedia/chproxy/tree/master/config#param_groups_config) ?

**Comment by komex** [comment]
@hagen1778, yes, this params are dynamically assigned, so user params are not a solution.

**Comment by hagen1778** [comment]
Thanks! I'll try to fix it.

**Comment by hagen1778** [comment]
pls see https://github.com/Vertamedia/chproxy/releases/tag/1.13.0
