### ISSUE TITLE
Audit log

### ISSUE THREAD

**Issue by lquerel** [Vertamedia/chproxy#48]
Add the ability to log INSERT and SELECT queries in an audit log for compliance purposes and performance analysis. Log partial sql statement, origin and the user-id of each query.

**Comment by hagen1778** [comment]
Hi @lquerel !
Why don't you use ClickHouse system.query_log table for that purpose? CHProxy populates every request user-agent with additional info: `Prepends User-Agent request header with remote/local address and in/out usernames before proxying it to ClickHouse, so this info may be queried from system.query_log.http_user_agent.`
So it should be easy to plot performance grpahs directly from ClickHouse. Consider following dashboards as template - https://grafana.com/dashboards/2515

**Comment by lquerel** [comment]
Thanks. I didn't notice the usernames were visible by clichhouse behind chproxy.
