### ISSUE TITLE
Please implement internal chproxy url for health checks

### ISSUE THREAD

**Issue by bzed** [Vertamedia/chproxy#53]
Hi,

checking if chproxy is still alive would be much easier if it would have an internal status/healph page, which returns 200 if everything is okay. Like clickhouse anwers with 200 on / and /ping.

Thanks,

bernd

**Comment by hagen1778** [comment]
Hi @bzed 

The common way to check app health is to query [/metrics](https://github.com/Vertamedia/chproxy/blob/master/main.go#L216) endpoint.

Also if you use [Prometheus](https://prometheus.io/) for your application monitoring you can get more insights of `chproxy` state. See [this link](https://github.com/Vertamedia/chproxy#metrics) for details.

**Comment by bzed** [comment]
Oh thanks a lot, somehow I completely failed to see /metrics in the documentation. Sorry for the noise!
