### ISSUE TITLE
spread insert replica 

### ISSUE THREAD

**Issue by cocopc** [Vertamedia/chproxy#64]
spread insert  replica , data insert only one node , eg:  replica1 : [node1 node2 ] replica2: [node3,node4]. insert data only into node1 or node2 or node3 or node4 . why not insert into (node1 and node3)  or (node2 and node4)

**Comment by hagen1778** [comment]
Hi @cocopc!
I'm not sure I understand your question. Could you plz provide configuration example and your use case?

**Comment by cocopc** [comment]
#### Hi @hagen1778 
##### configuration
`
clusters:
  - name: "replica-write"
    replicas:
      - name: "replica1"
        nodes: ["node1:8123", "node2:8123"]
      - name: "replica2"
        nodes: ["node3:8123","node4:8123"]
`
* cluster has replica1 and replica2 ,when insert into local table(not  distributed table), data only insert into one node.  eg: data insert into node1, but node3 not insert data. how to guarantee  high availability

**Comment by hagen1778** [comment]
There is no sense in inserting the same request into replica1.node1 and replica2.node3 or replica1.node2 and replica2.node4. ClickHouse supports [internal replication](https://clickhouse.yandex/docs/en/operations/table_engines/replication/) between tables which would be much more reliable and efficient than duplicating requests.

**Comment by cocopc** [comment]
Thank you, but internal replication depend on zookeeper.   if use zk , whether it causes insert performance degradation and managing clusters is more difficult ?

**Comment by hagen1778** [comment]
@cocopc the only difficulty in my opinion is to install and configure ZK. It won't cause degradation up to some point(i.e. you have x10 replicas ), but it will guarantee data consistency which is more important. In you approach you are trying to insert the same data into two nodes, but what if one of the replicas is down? Eventually, you'll get different datasets in replicas. When CH and ZK guarantee you data consistency in such cases.

**Comment by cocopc** [comment]
@hagen1778 I see, Thanks a million！
