### ISSUE TITLE
Do not print loaded config to a log file

### ISSUE THREAD

**Issue by PhantomPhreak** [Vertamedia/chproxy#65]
By design, all passwords stored in the config file in a plaintext. During config loading/reloading, whole config including passwords will be printed to the log:
https://github.com/Vertamedia/chproxy/blob/master/main.go#L272

We're running chproxy in a docker, and collecting logs from a service for further analysis. Passwords stored in a log file creating a security issue for us.
Also, i think it's useful to print a loaded config while debugging (with a `log_debug = true`), but makes no sense during a normal operation.

Is it possible print the config only with a `log_debug = true` only? Or at least hide a passwords somehow?

Thanks!

**Comment by hagen1778** [comment]
Yeah, secrets should hidden. I imagine it like following:
```
// Auth is a structure for holding creds
type Auth struct {
	// CH user name
	User string `yaml:"user"`

	// CH user password
	Password string `yaml:"password"`

	// Catches all undefined fields
	XXX map[string]interface{} `yaml:",inline"`
}

func (a Auth) String() string {
	return fmt.Sprintf("user: %q\npassword: <secret>", a.User)
}

func (a Auth) MarshalYAML() (interface{}, error) {
	return a.String(), nil
}
```

Would be great to have this implemented
