### ISSUE TITLE
Format specifier is incorrect in scope.go causing resulting in 'go test' failure

### ISSUE THREAD

**Issue by macdonsp** [Vertamedia/chproxy#73]
Running 'go test' on master results in:

    ./scope.go:82:9: Sprintf format %s has arg time.Since(s.startTime).Nanoseconds() / 1000.0 of wrong type int64

This was introduced in https://github.com/Vertamedia/chproxy/pull/70 which changed the value from a Duration to int64 without updating the format specifier

**Comment by hagen1778** [comment]
Should be resolved in master and next release!
