### ISSUE TITLE
Log functions enhancement

### ISSUE THREAD

**Issue by weiqxu** [Vertamedia/chproxy#75]
The log function is very simple now. When using it in production environment, I think it's better to have some more function. First, it's better to have the log rotation and the log path can be config. The second is the log file size limit can be set. 

Does the core team have this plan in the Roadmap.  or we can discuss it here, and if more people think it is useful, I can implement it after more details have been discussed.

**Comment by hagen1778** [comment]
Hi @weiqxu! There are no such plans for logging. The responsibility for log rotation is usually held by other applications, like supervisord when just running binaries or by docker/k8s when running containers. I bet there are more options which could help to solve this as well, so no need in additional functionality from my perspective.
