### ISSUE TITLE
Releases schedule

### ISSUE THREAD

**Issue by gemini1389** [Vertamedia/chproxy#80]
Can you tell me about the release schedule? You have some release schedule? When is the next release planned?

Thanks!

**Comment by hagen1778** [comment]
Hi @gemini1389! There is no release schedule) The project updates are rare so it is always depends on amount of changes collected since last release.
@valyala can you have a look and cut a new release please?

**Comment by valyala** [comment]
Released [v1.14.0](https://github.com/Vertamedia/chproxy/releases).
