### ISSUE TITLE
Empty Authorization header will lead to 400 bad request

### ISSUE THREAD

**Issue by yonatang** [Vertamedia/chproxy#81]
Trying to post a query with an empty `Authorization` header will lead to a 400 response.

For example, the following will fail through chproxy, while it would work when submitted directly to CH node:
```
nc 127.0.0.1 8123
POST /?user=default&database=default&compress=1 HTTP/1.1
Authorization
Content-Type: text/plain; charset=UTF-8
User-Agent: Java/11.0.1
Host: localhost:8123
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 55

select timezone() FORMAT TabSeparatedWithNamesAndTypes
```

Notice that this type of request is generated by the https://github.com/blynkkk/clickhouse4j JDBC driver, which is quite popular.

**Comment by hagen1778** [comment]
Hi @yonatang! Which version of chproxy is this?

**Comment by yonatang** [comment]
Latest, but I after I forked it to create PR I saw that clickhouse4j resolved it in https://github.com/yonatang/clickhouse4j/commit/195816ae3ea8737ae9360fe7be884af0bc2f9b78 10 days ago.

**Comment by yonatang** [comment]
Hi @hagen1778, I was able to confirm the issue relays in a different layer - the LB that we use in our k8s rejects that header.  Closing the issue.
