### ISSUE TITLE
keep alive with upstream

### ISSUE THREAD

**Issue by slimtom95** [Vertamedia/chproxy#85]
I found chproxy closes each connection with upstream server very soon, like within a second.  With hundreds and thousands of concurrent requests, available ports can be easily run out - since most of them would be at TIME_WAIT state.

Can we import some connection pool sort of ideas to keep a custom number of active connections with upstream servers, or set a custom keep alive time with upstream server for each cluster, or honor the CH keep alive time in the response headers?

**Comment by hagen1778** [comment]
Hi @slimtom95 !
Chproxy supports keep-alive from client to proxy, but not from clients to CH. This is because it uses standard golang reverse-proxy implementation which satisfies the HTTP standard. Pls see more here https://golang.org/src/net/http/httputil/reverseproxy.go#L142

**Comment by slimtom95** [comment]
Thanks for the clarification. Finally found that my problem could be solved by adding followings(with side-effects):
```
http.DefaultTransport.(*http.Transport).MaxIdleConns = 500
http.DefaultTransport.(*http.Transport).MaxIdleConnsPerHost = 100
```
Refered to
[link](https://stackoverflow.com/questions/46580313/go-http-server-bad-performance-on-request-forwarding)
