### ISSUE TITLE
Can the chproxy configuration be dynamically updated？

### ISSUE THREAD

**Issue by sunny19930321** [Vertamedia/chproxy#87]
Configuration may be updated without restart - just send SIGHUP signal to chproxy process.

**Comment by hagen1778** [comment]
Hi @sunny19930321! I don't understand the question. Could you pls elaborate?

**Comment by sunny19930321** [comment]
> Hi @sunny19930321! I don't understand the question. Could you pls elaborate?
I don't understand the question. Could you pls elaborate?

./chproxy -config=/path/to/config.yml, this command starts chproxy, can you update the configuration without restarting chproxy？

**Comment by hagen1778** [comment]
Yes, just send SIGHUP signal to the process:
`kill -SIGHUP `pidof chproxy``

**Comment by sunny19930321** [comment]
> Yes. You can send SIGHUP signal via command `kill`. Kill command help says:
> 
> ```
> kill [-s signal_name] pid ...
> ```
> 
> So we need to send `-SIGHUP` signal to the chproxy pid. To get the pid we execute:
> `pidof chproxy`
> It should return the ID of the process.
> 
> So the full command will be following:
> `kill -SIGHUP 'pidof chproxy'`
> 
> After receiving SIGHUP chproxy should print a log message:
> `SIGHUP received. Going to reload config...`

Ok, thank you @hagen1778

**Comment by hagen1778** [comment]
Cool! Feel free to reopen if you have questions
