### ISSUE TITLE
Can I access port 9000 via chproxy ?

### ISSUE THREAD

**Issue by VitoLiao** [Vertamedia/chproxy#89]
When I config chproxy to access CH by port 9000, the log of chproxy show connect error.Is there any way can access CH by chproxy via port 9000 ?

**Comment by hagen1778** [comment]
Hi @VitoLiao! Port `9000` is a TCP port for native console client - see https://clickhouse.tech/docs/en/interfaces/tcp/
And chproxy is an HTTP reverse proxy that supposed to work with ClickHouse HTTP port 8123.

**Comment by VitoLiao** [comment]
@hagen1778 okay, I got it,  thank you so much !
