### ISSUE TITLE
How chproxy spread INSERT

### ISSUE THREAD

**Issue by Fanduzi** [Vertamedia/chproxy#91]
```
users:
  - name: "insert"
    to_cluster: "stats-raw"
    to_user: "default"

clusters:
  - name: "stats-raw"

    # Requests are spread in `round-robin` + `least-loaded` fashion among nodes.
    # Unreachable and unhealthy nodes are skipped.
    nodes: [
      "10.10.10.1:8123",
      "10.10.10.2:8123",
      "10.10.10.3:8123",
    ]
```
Take the above configuration as an example
What I don't understand is how chproxysql executes INSERT statements

i.e
request A , B, C. A have 10 INSERT statement and insert 10 rows, B 100 INSERT..., C 1000 INSERT...
A, B, C will send to 10.10.10.1, 10.10.10.2, 10.10.10.3 respectively, so 10.10.10.1 have 10 record in local table, 10.10.10.2 have 100, 10.10.10.3 have 1000?
OR
the totoal 10+100+1000=1110 rows will Insert three nodes evenly?

sorry for my poor english

**Comment by valyala** [comment]
The whole INSERT statements are spread among the configured servers. `chproxy` doesn't route independently individual rows from INSERT statements. It is expected that the number of INSERT statements is big. In this case there resulting number of rows should be roughly equal among the configured servers even if the number of rows per each INSERT varies significantly.

**Comment by Fanduzi** [comment]
> The whole INSERT statements are spread among the configured servers. `chproxy` doesn't route independently individual rows from INSERT statements. It is expected that the number of INSERT statements is big. In this case the resulting number of rows should be roughly equal among the configured servers even if the number of rows per each INSERT varies significantly.

thank you @valyala , I understand

**Comment by lddlww** [comment]
@valyala does chproxy insert rows/3 to per node（10.10.10.1:8123，10.10.10.2:8123，10.10.10.3:8123）?
